mavros:
  ros__parameters:
    plugin_allowlist: [
      "sys_*",
      "command",
      "local_position",
      "setpoint_position",
      "imu",
    ]

mavros_node:
  ros__parameters:
    fcu_url: "udp://127.0.0.1:14550@"

mavros/local_position:
  ros__parameters:
    tf:
      send: true
